# MODULE FunctionDoesNotExistError_test.uhll
# ERROR in Line 10 Col 5
# 
#     foo()
#     ^
# Function does not exist

fn main()
{
    foo()
}